### ISSUE TITLE
earlystopping

### ISSUE THREAD

**Issue by Annsas** [FengAoWang/TMO-Net#3]
论文中提到预训练时使用了earlystopping，但是给出的代码中没看见在哪里使用

**Comment by FengAoWang** [comment]
early stopping是训练中常用trick，不是训练中的核心代码，因此没有给出。结合五折交叉验证，你可以挑选在验证集上性能最好的模型，防止模型过拟合。

**Comment by Annsas** [comment]
好的，非常感谢
