### ISSUE TITLE
Could you please share the train and test index csv files?

### ISSUE THREAD

**Issue by WangMengxiao319** [FengAoWang/TMO-Net#5]
Thanks for your talented work! But I didn't found the two files to split the dataset. What is the structure in these files? Could you please give an example? Only index number include ?
```
train_index_path = '../data/train_data.csv'
test_index_path = '../data/test_data.csv'
```

**Comment by FengAoWang** [comment]
You can use the module 'StratifiedKFold' of package'sklearn' to randomly spilit the data into train and test index for 5 folds by cancer type and os event. The format of index file is like this:
<img width="318" alt="截屏2024-07-22 09 58 12" src="https://github.com/user-attachments/assets/5f9ae9cc-f699-4e5b-b23b-5bae1b514098">
Of course, you can redefine a new 'Dataset' Class to run the model.

**Comment by WangMengxiao319** [comment]
thanks a lot!
