### ISSUE TITLE
请问第三个实验验证，乳腺癌亚型分类，matedataset 的每个模态的特征维度为15592，和预训练的tmo-net模型的模态输入维度不同，请问具体是如何处理的，是通过基因名从15592中匹配对应模态特征的基因名吗？

### ISSUE THREAD

**Issue by Sarahsus** [FengAoWang/TMO-Net#6]
pretrained tmo net:    model = TMO_Net(4, [6016, 6617, 4539, 7460], 64,
                    [2048, 512], [512, 2048], omics_data_type, 0.01)
    torch.cuda.set_device(device_id)
metadataset: model = DownStream_predictor(4, [15592,15592], 64, [2048, 512],
                                 [512, 2048], pretrain_model_path, task, omics_data_type, fixed, omics, 0.01)

**Comment by FengAoWang** [comment]
你好，通过基因名从15592中匹配对应的特征，缺失的特征补0，得到和预训练相同的模态输入维度。在所有的下游任务实验中，所有的模态都是通过这样方式进行匹配。

**Comment by Sarahsus** [comment]
好的，非常感谢
