### ISSUE TITLE
metadataset 中的label是否有误，与论文中的luminal A, luminal B 无法匹配

### ISSUE THREAD

**Issue by Sarahsus** [FengAoWang/TMO-Net#7]
omics_data, ERStatus, HER2Status, Pam50Subtype, BasalNonBasal, Pam50SubtypeSingleLuminal, Luminal = data
 ERStatus, HER2Status, Pam50Subtype, BasalNonBasal, Pam50SubtypeSingleLuminal, Luminal 这些里面没有luminal A, luminal B

**Comment by FengAoWang** [comment]
请仔细阅读论文和数据集，metabric做了ERStatus, HER2Status, Pam50Subtype, BasalNonBasal四种分类任务。Basal，HER2，Luminal A, Luminal B是Pam50Subtype分类任务中的四种亚型。另外这个任务更多信息你可以参考Moanna: Multi-Omics Autoencoder-Based Neural Network Algorithm for Predicting Breast Cancer Subtypes这篇文章。

**Comment by Sarahsus** [comment]
> 请仔细阅读论文和数据集，metabric做了ERStatus, HER2Status, Pam50Subtype, BasalNonBasal四种分类任务。Basal，HER2，Luminal A, Luminal B是Pam50Subtype分类任务中的四种亚型。另外这个任务更多信息你可以参考Moanna: Multi-Omics Autoencoder-Based Neural Network Algorithm for Predicting Breast Cancer Subtypes这篇文章。

好的，谢谢
